version: 3

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  lint:staged:
    cmds:
      - git diff --cached > /tmp/stage.patch
      - defer: rm /tmp/stage.patch
      - golangci-lint run --new-from-patch=/tmp/stage.patch

  test:
    cmds:
      - go test -v `go list ./... | grep -v -e './examples' -e './test'` --cover
  test:report:
    cmds:
      - go test -v `go list ./... | grep -v -e './examples' -e './test'` --coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  run:example:base:
    cmds:
      - go run main.go serve
    dir: examples/base

  # Generate docs
  # Require gomarkdoc (https://github.com/princjef/gomarkdoc)
  docs:
    cmds:
      - go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
      - gomarkdoc -o README.md -e .